### ISSUE TITLE
Automatic indentation removal

### ISSUE THREAD

**Issue by ecton** [PsichiX/md-bakery#1]
Great project. I'm adopting it right now, and I have one suggestion for a feature. When using snippets that are completely indented, ie:

```rust
{
    // [md-bakery: begin @ snippet-b]
    let db =
        Storage::<Shape>::open_local("view-examples.pliantdb", &Configuration::default()).await?;
    // [md-bakery: end]
}
```

The baked markdown includes the preceding whitespace on the lines. I would prefer if it stripped identical whitespace when it's present on all of the snippet lines.

**Comment by PsichiX** [comment]
that's a great idea! gonna turn it into task and ping you with PR :D

**Comment by PsichiX** [comment]
@ecton fixed in version 1.1.0 :D

**Comment by PsichiX** [comment]
or not completely fixed, i'm sorry i forgot about empty lines, gonna quick fix that too in a second!

**Comment by ecton** [comment]
For my particular snippets, it worked perfectly. :+1: 

Thanks for the update!

**Comment by PsichiX** [comment]
great!
anyway, new version with empty lines fix is published :)
